language: node_js
node_js:
  - '10.15.3'

branches:
  only:
    - master

before_script:
 - npm install -g @angular/cli

cache:
  directories:
    - node_modules

script:
  - ng build --prod
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB
  local_dir: ./dist/BiothroomApp
  on:
    branch: master